exclude: settings/|/__init__\.py$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
  - id: isort
    name: isort (python)

- repo: local
  hooks:
    - id: run-pre-commit-on-changed-files
      name: Run pre-commit on changed files
      entry: python /scripts/run_pre_commit_on_changed_files.py
      language: system
      types: [python,jsx]
      args: [--exclude=__init__\.py$]
    - id: check-console-log
      name: Check for console.log statements in .jsx files
      entry: python ./scripts/check_console_log.py
      language: python
      types: [jsx]
    - id: check-print
      name: Check for print statements in python files
      entry: python ./scripts/check_print.py
      language: python
      types: [python]
