# Generated by Django 5.1.6 on 2025-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_charactercondition_player_remove_player_lobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
