# Generated by Django 5.1.6 on 2025-02-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_condition_conditiontype_remove_character_lobby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercondition',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.AddField(
            model_name='charactercondition',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.character'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerInLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DM', 'Dungeon Master'), ('P', 'Player'), ('PA', 'Player Admin')], max_length=2)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby', to='players.lobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='players.player')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerinlobby'),
        ),
    ]
