# Generated by Django 5.1.6 on 2025-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_lobby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
