# Generated by Django 5.1.6 on 2025-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_lobby_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='character',
            name='current_trun',
            field=models.BooleanField(default=False),
        ),
    ]
