# Generated by Django 5.1.6 on 2025-02-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_character_options_character_current_trun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='current_trun',
            new_name='current_turn',
        ),
    ]
