# Generated by Django 5.1.6 on 2025-04-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_rename_current_trun_character_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='debuffed',
            field=models.BooleanField(default=False),
        ),
    ]
