# Generated by Django 5.1.6 on 2025-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_character_debuffed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='debuffed',
        ),
        migrations.AddField(
            model_name='character',
            name='debuff',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
