# Generated by Django 5.1.6 on 2025-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_remove_character_debuffed_character_debuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='reminder',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
