# Generated by Django 5.1.6 on 2025-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_character_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stat_block',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='template',
            field=models.CharField(choices=[('W', 'Weak'), ('N', 'Normal'), ('E', 'Elite')], default='N', max_length=1),
        ),
    ]
