# Generated by Django 5.1.6 on 2025-09-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_character_stat_block_character_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='condition',
            name='conditionType',
        ),
        migrations.AlterField(
            model_name='character',
            name='stat_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.statblock'),
        ),
        migrations.DeleteModel(
            name='CharacterCondition',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='ConditionType',
        ),
    ]
