# Generated by Django 5.1.6 on 2025-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_statblock_remove_condition_conditiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='template',
            field=models.CharField(choices=[('weak', 'Weak'), ('normal', 'Normal'), ('elite', 'Elite')], default='normal', max_length=6),
        ),
    ]
