# Generated by Django 5.1.6 on 2025-09-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_character_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statblock',
            name='data',
        ),
    ]
