# Generated by Django 5.1.6 on 2025-09-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_remove_statblock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='stat_block',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
