# Generated by Django 5.1.6 on 2025-09-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_character_stat_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatBlock',
        ),
    ]
