# Generated by Django 5.1.6 on 2025-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_delete_statblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
    ]
