# Generated by Django 5.1.6 on 2025-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_character_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_reactions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='max_reactions',
            field=models.IntegerField(default=1),
        ),
    ]
