# Generated by Django 5.1.6 on 2025-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_character_current_reactions_character_max_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
