# Generated by Django 3.1.12 on 2025-12-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_auto_20250929_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='player',
            new_name='player_lobby',
        ),
    ]
